name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 2 * * *'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test Project

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Check Formatting
      run: cargo fmt --all -- --check

    - name: Cargo Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build project
      run: cargo build --all-features

    - name: Test project
      run: cargo test --all-features --workspace

    - name: Run clippy
      uses: giraffate/clippy-action@v1
      with:
        reporter: 'github-pr-check'
        clippy_flags: --no-deps --tests
        filter_mode: nofilter
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docs
      env:
        RUSTDOCFLAGS: -D warnings
      run: cargo doc --all-features --no-deps --workspace --document-private-items
